# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee33cc71c034d65853d8c12ce00e3d1373d236d97a2cfe61d04723623bf540b4de7c4b4b95064029137e9b333e629c05089d82238aec42ecf26ec8f1a4737ce

test:
  secret_key_base: 13b06488cc954c3c532595d9748af4446da0f517faa580485791b5be6ef4cbd02ce35dd5637d93e8e757cf86b6ede7c820f5e123f31d2ad88878a9eda57472fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
